const P=[
 [1,'Ambo Aura','Médicos',54900,'Más elegido','https://images.pexels.com/photos/9048351/pexels-photo-9048351.jpeg?auto=compress&cs=tinysrgb&w=900',['#7ca9b4','#324e59','#c8b9ae']],
 [2,'Ambo Siena','Médicos',57900,'Nuevo','https://images.pexels.com/photos/14438790/pexels-photo-14438790.jpeg?auto=compress&cs=tinysrgb&w=900',['#d8d7d2','#638291','#303d45']],
 [3,'Chaqueta Alba','Gastronomía',48900,'','https://images.unsplash.com/photo-1583394293214-28ded15ee548?auto=format&fit=crop&w=900&q=85',['#f2f0ea','#242d31','#a9b8bc']],
 [4,'Delantal Bruma','Gastronomía',36900,'','https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=85',['#c7a987','#53676d','#1e292c']],
 [6,'Ambo Mini','Pediatría',52900,'','https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=900&q=85',['#9fc9d0','#d4b7be','#829b83']]
].map(x=>({id:x[0],name:x[1],category:x[2],price:x[3],badge:x[4],image:x[5],colors:x[6]}));
const C=['Todos','Médicos','Gastronomía','Pediatría'],$=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);let filter='Todos',cart=JSON.parse(localStorage.getItem('sb-cart')||'[]').filter(i=>P.some(p=>p.id===i.id)),checkout=false;
window.addEventListener('load',()=>setTimeout(()=>$('.loader').classList.add('done'),1100));const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});function observe(){document.querySelectorAll('.reveal').forEach(x=>obs.observe(x))}
function filters(){$('#filters').innerHTML=C.map(c=>`<button class="${filter===c?'active':''}" data-f="${c}">${c}</button>`).join('');document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{filter=b.dataset.f;filters();products()})}
function products(){let list=filter==='Todos'?P:P.filter(p=>p.category===filter);$('#products').innerHTML=list.map(p=>`<article class="card reveal" data-id="${p.id}"><div class="productImage">${p.badge?`<span>${p.badge}</span>`:''}<img src="${p.image}" alt="${p.name}"><button class="add">+</button></div><div class="cardInfo"><small>${p.category}</small><div class="nameRow"><h3>${p.name}</h3><b>${money(p.price)}</b></div><div class="options"><div class="miniSwatches">${p.colors.map((c,i)=>`<button class="color ${!i?'selected':''}" data-color="${c}" style="background:${c}"></button>`).join('')}</div><select><option>XS</option><option>S</option><option selected>M</option><option>L</option><option>XL</option><option>XXL</option></select></div></div></article>`).join('');document.querySelectorAll('.card').forEach(card=>{card.querySelectorAll('.color').forEach(c=>c.onclick=()=>{card.querySelectorAll('.color').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')});card.querySelector('.add').onclick=()=>add(P.find(x=>x.id==card.dataset.id),card.querySelector('select').value,card.querySelector('.selected').dataset.color)});observe()}
function add(p,size='M',color=p.colors[0]){let x=cart.find(i=>i.id===p.id&&i.size===size&&i.color===color);x?x.qty++:cart.push({...p,size,color,qty:1});save();toast(`${p.name} agregado`)}function save(){localStorage.setItem('sb-cart',JSON.stringify(cart));let n=cart.reduce((s,i)=>s+i.qty,0);$('#cartCount').textContent=n;$('#drawerCount').textContent=`${n} ${n===1?'producto':'productos'}`;renderCart()}function toast(t){let e=$('#toast');e.textContent=`✓ ${t}`;e.hidden=false;setTimeout(()=>e.hidden=true,1800)}
function renderCart(){let v=$('#cartView'),total=cart.reduce((s,i)=>s+i.price*i.qty,0);if(checkout){v.innerHTML=`<form class="checkout" id="checkout"><button type="button" class="back" id="back">← Volver</button><h4>Datos de envío</h4><label>Nombre y apellido<input required name="nombre"></label><label>Teléfono<input required name="telefono"></label><label>Dirección<input required name="direccion"></label><label>Localidad / Provincia<input required name="localidad"></label><label>Notas<textarea name="notas"></textarea></label><div class="summary"><div><span>Total</span><b>${money(total)}</b></div><button class="whatsapp">Enviar pedido por WhatsApp ↗</button></div></form>`;$('#back').onclick=()=>{checkout=false;renderCart()};$('#checkout').onsubmit=whatsapp;return}if(!cart.length){v.innerHTML=`<div class="empty"><span>SB</span><h4>Tu bolsa está esperando</h4><p>Elegí tu uniforme favorito.</p><button id="see">Ver colección</button></div>`;$('#see').onclick=close;return}v.innerHTML=`<div class="cartItems">${cart.map((i,n)=>`<div class="cartItem"><img src="${i.image}"><div><b>${i.name}</b><small>Talle ${i.size} · <i style="background:${i.color}"></i></small><div class="qty"><button data-n="${n}" data-d="-1">−</button><span>${i.qty}</span><button data-n="${n}" data-d="1">+</button></div></div><strong>${money(i.price*i.qty)}</strong></div>`).join('')}</div><div class="summary"><div><span>Subtotal</span><b>${money(total)}</b></div><small>El envío se coordina por WhatsApp.</small><button class="primary" id="checkoutBtn">Continuar →</button></div>`;document.querySelectorAll('.qty button').forEach(b=>b.onclick=()=>{let n=+b.dataset.n;cart[n].qty+=+b.dataset.d;if(cart[n].qty<1)cart.splice(n,1);save()});$('#checkoutBtn').onclick=()=>{checkout=true;renderCart()}}
function whatsapp(e){e.preventDefault();let f=new FormData(e.target),total=cart.reduce((s,i)=>s+i.price*i.qty,0),lines=cart.map(i=>`• ${i.name} — Talle ${i.size} — ${i.qty} u. — ${money(i.price*i.qty)}`).join('\n'),msg=`Hola Uniformes SB 👋 Quiero realizar este pedido:\n\n${lines}\n\nTotal: ${money(total)}\n\nNombre: ${f.get('nombre')}\nTeléfono: ${f.get('telefono')}\nDirección: ${f.get('direccion')}, ${f.get('localidad')}\nNotas: ${f.get('notas')||'—'}`;window.open(`https://wa.me/5491100000000?text=${encodeURIComponent(msg)}`,'_blank')}
function open(){checkout=false;renderCart();$('#drawer').classList.add('show');$('#drawerShade').classList.add('show')}function close(){$('#drawer').classList.remove('show');$('#drawerShade').classList.remove('show')}$('#openCart').onclick=open;$('#closeCart').onclick=close;$('#drawerShade').onclick=close;$('#featuredAdd').onclick=()=>add(P[0]);filters();products();save();observe();
