'use strict';
// Agregar el número real con código de país, sin + ni espacios.
const WHATSAPP_NUMBER = '5491153132095';
const icons={bag:'<path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',search:'<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',layers:'<path d="m12 3 10 6-10 6L2 9l10-6Zm-10 12 10 6 10-6M2 12l10 6 10-6"/>',chat:'<path d="M21 11.5a9 9 0 0 1-9 9 10 10 0 0 1-4-.8L3 21l1.3-5A9 9 0 1 1 21 11.5Z"/><path d="M8 11h8"/>',truck:'<path d="M2 5h12v12H2zM14 9h4l4 5v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',ruler:'<path d="m3 16 13-13 5 5L8 21zM8 11l3 3M12 7l3 3M5 14l3 3"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.grid}</svg>`;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const P=[
{id:1,name:'Ambo Aura',category:'Médicos',price:54900,badge:'Más elegido',image:'assets/products/ambo-aura.jpg',colors:['#7ca9b4','#324e59','#c8b9ae'],colorNames:['Celeste','Azul profundo','Arena'],description:'Tu mejor versión, en cada jornada. Un ambo que combina comodidad y presencia.'},
{id:2,name:'Ambo Siena',category:'Médicos',price:57900,badge:'Nuevo',image:'assets/products/ambo-siena.jpg',colors:['#d8d7d2','#638291','#303d45'],colorNames:['Perla','Azul grisáceo','Grafito'],description:'Líneas simples, estilo propio. Un compañero para el ritmo de tu profesión.'},
{id:3,name:'Chaqueta Alba',category:'Gastronomía',price:48900,badge:'',image:'assets/products/chaqueta-alba.jpg',colors:['#f2f0ea','#242d31','#a9b8bc'],colorNames:['Blanco','Negro','Gris'],description:'La pasión también se viste. Presencia y comodidad para tu cocina.'},
{id:4,name:'Delantal Bruma',category:'Gastronomía',price:36900,badge:'',image:'assets/products/delantal-bruma.jpg',colors:['#c7a987','#53676d','#1e292c'],colorNames:['Camel','Petróleo','Negro'],description:'Ese detalle que completa tu estilo. Para crear, servir y disfrutar lo que hacés.'},
{id:6,name:'Ambo Mini',category:'Pediatría',price:52900,badge:'',image:'assets/products/ambo-mini.jpg',colors:['#9fc9d0','#d4b7be','#829b83'],colorNames:['Celeste suave','Rosa','Verde salvia'],description:'Calidez en cada encuentro. Un uniforme para acompañar a los más chicos.'}
];
const sizes=['XS','S','M','L','XL','XXL'],categories=['Todos','Médicos','Gastronomía','Pediatría'];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
let stored=read('sb-cart',[]),cart=(Array.isArray(stored)?stored:[]).filter(i=>i&&P.some(p=>p.id===i.id)&&sizes.includes(i.size)&&Number.isFinite(i.qty)&&i.qty>0).map(i=>{let p=P.find(p=>p.id===i.id);return{id:p.id,size:i.size,color:p.colors.includes(i.color)?i.color:p.colors[0],qty:Math.min(99,Math.floor(i.qty))}});
let savedFavorites=read('sb-favorites',[]),favorites=new Set(Array.isArray(savedFavorites)?savedFavorites.filter(id=>P.some(p=>p.id===id)):[]),filter='Todos',query='',sort='featured',favoritesOnly=false,grid=false,toastTimer,checkoutData={},detailChoice={};
const selections=new Map(P.map(p=>[p.id,{size:'M',color:p.colors[0]}]));
function hydrateIcons(root=document){root.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon))}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function filters(){$('#filters').innerHTML=categories.map(c=>`<button data-filter="${c}" aria-pressed="${filter===c}">${c}</button>`).join('')}
function swatches(p,selected){return p.colors.map((c,i)=>`<button class="swatch" style="background:${c}" data-color="${c}" aria-label="${p.colorNames[i]}" title="${p.colorNames[i]}" aria-pressed="${selected===c}"></button>`).join('')}
function products(){let q=query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();let list=P.filter(p=>(filter==='Todos'||p.category===filter)&&(!favoritesOnly||favorites.has(p.id))&&(p.name+' '+p.category).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q));if(sort!=='featured')list.sort((a,b)=>sort==='price-low'?a.price-b.price:b.price-a.price);$('#result-count').textContent=`${list.length} prendas · ${favoritesOnly?'Tus favoritos':'Toda la colección'}`;$('#empty-results').hidden=!!list.length;$('#products').innerHTML=list.map((p,i)=>{let sel=selections.get(p.id);return `<article class="product" data-id="${p.id}" aria-label="${p.name}"><div class="product-photo"><button class="photo-open" data-detail="${p.id}" aria-label="Ver ${p.name}"><img src="${p.image}" alt="${p.name}" ${i>1?'loading="lazy"':''}></button>${p.badge?`<span class="product-tag">${p.badge}</span>`:''}</div><button class="favorite" data-favorite="${p.id}" aria-label="Guardar ${p.name} en favoritos" aria-pressed="${favorites.has(p.id)}">${icon('heart')}</button><span class="product-counter">${String(i+1).padStart(2,'0')} / ${String(list.length).padStart(2,'0')}</span><span class="swipe-hint">DESLIZÁ PARA EXPLORAR ↓</span><div class="product-info"><span class="product-category">${p.category} / UNIFORMES SB</span><div class="product-title-row"><h3>${p.name}</h3><strong class="product-price">${money(p.price)}</strong></div><p class="product-description">${p.description}</p><div class="product-options"><div class="swatches" role="group" aria-label="Color de ${p.name}">${swatches(p,sel.color)}</div><label class="size-label">Talle <select data-size aria-label="Talle de ${p.name}">${sizes.map(s=>`<option ${s===sel.size?'selected':''}>${s}</option>`).join('')}</select></label></div><div class="product-buttons"><button class="button detail-button" data-detail="${p.id}">Ver detalles <span>↗</span></button><button class="button primary" data-add="${p.id}">Agregar <span>+</span></button></div></div></article>`}).join('');$('#products').scrollTop=0;attachImageFallbacks()}
function attachImageFallbacks(){$$('img').forEach(img=>{img.onerror=()=>{img.onerror=null;img.classList.add('image-unavailable');img.alt='No se pudo cargar la foto de '+img.alt;}})}
function sync(){persist('sb-cart',cart);let count=cart.reduce((s,i)=>s+i.qty,0);$$('[data-count]').forEach(e=>e.textContent=count);$('#drawer-count').textContent=`(${count})`}
function add(id,choice){let p=P.find(p=>p.id===id),sel=choice||selections.get(id);let item=cart.find(i=>i.id===id&&i.size===sel.size&&i.color===sel.color);if(item){if(item.qty>=99){toast('Máximo de 99 unidades por variante');return}item.qty++}else cart.push({id,size:sel.size,color:sel.color,qty:1});sync();toast(`${p.name} agregado a tu bolsa`)}
function show(dialog){dialog.showModal()}
function details(id){let p=P.find(p=>p.id===id);detailChoice={...selections.get(id)};$('#product-detail').innerHTML=`<div class="detail-layout"><img class="detail-image" src="${p.image}" alt="${p.name}"><div class="detail-copy"><span class="product-category">${p.category} / UNIFORMES SB</span><h2 id="product-title">${p.name}</h2><p>${p.description}</p><strong class="detail-price">${money(p.price)}</strong><span class="choice-label">Color: <b id="color-name">${p.colorNames[p.colors.indexOf(detailChoice.color)]}</b></span><div class="swatches" role="group" aria-label="Color">${swatches(p,detailChoice.color)}</div><span class="choice-label">Elegí tu talle</span><div class="sizes" role="group" aria-label="Talle">${sizes.map(s=>`<button data-detail-size="${s}" aria-pressed="${s===detailChoice.size}">${s}</button>`).join('')}</div><button class="button primary" id="detail-add">Agregar a mi bolsa <span>+</span></button><p class="detail-note">Talles XS al XXL · Envíos a todo el país.<br>Consultá medidas y disponibilidad antes de confirmar. La foto no cambia al seleccionar un color.</p></div></div>`;$('#product-detail').onclick=e=>{const c=e.target.closest('[data-color]'),s=e.target.closest('[data-detail-size]');if(c){detailChoice.color=c.dataset.color;$('#color-name').textContent=p.colorNames[p.colors.indexOf(detailChoice.color)];$$('#product-detail [data-color]').forEach(b=>b.setAttribute('aria-pressed',b===c))}if(s){detailChoice.size=s.dataset.detailSize;$$('[data-detail-size]').forEach(b=>b.setAttribute('aria-pressed',b===s))}};$('#detail-add').onclick=()=>{selections.set(id,{...detailChoice});add(id,detailChoice);$('#product-dialog').close()};attachImageFallbacks();show($('#product-dialog'))}
function cartTotal(){return cart.reduce((s,i)=>s+P.find(p=>p.id===i.id).price*i.qty,0)}
function renderCart(){if(!cart.length){$('#cart-view').innerHTML=`<div class="empty-cart">${icon('bag')}<h3>Tu próximo favorito<br>te está esperando.</h3><p>Explorá la colección y armá tu bolsa.</p><button class="button primary" id="browse">Descubrir colección ↗</button></div>`;$('#browse').onclick=()=>$('#cart-dialog').close();return}$('#cart-view').innerHTML=`<div class="cart-items">${cart.map((item,n)=>{let p=P.find(p=>p.id===item.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><small>Talle ${item.size} · ${p.colorNames[p.colors.indexOf(item.color)]}</small><div class="cart-line"><div class="qty"><button data-qty="${n}" data-delta="-1" aria-label="Quitar una unidad de ${p.name}">−</button><span>${item.qty}</span><button data-qty="${n}" data-delta="1" aria-label="Sumar una unidad de ${p.name}">+</button></div><strong>${money(p.price*item.qty)}</strong></div><button class="remove-item" data-remove="${n}">Eliminar</button></div></div>`}).join('')}</div><div class="cart-summary"><div class="total-row"><span>Subtotal</span><strong>${money(cartTotal())}</strong></div><p>Envío a coordinar. Disponibilidad a confirmar.<br>No se realiza ningún cobro en esta página.</p><button class="button primary" id="checkout-button">Continuar con mi pedido <span>→</span></button></div>`;$('#checkout-button').onclick=checkout;attachImageFallbacks()}
function checkout(){if(!cart.length){renderCart();return}$('#cart-view').innerHTML=`<form class="checkout" id="checkout-form"><button class="text-button" type="button" id="back-to-cart">← Volver a mi bolsa</button><h3>Preparemos tu pedido.</h3><p>Completá tus datos para coordinar la compra y el envío.</p><label>Nombre y apellido<input name="nombre" required autocomplete="name" maxlength="100"></label><label>Teléfono<input name="telefono" type="tel" required autocomplete="tel" maxlength="40"></label><label>Dirección<input name="direccion" required autocomplete="street-address" maxlength="200"></label><label>Localidad / Provincia<input name="localidad" required autocomplete="address-level2" maxlength="150"></label><label>Notas (opcional)<textarea name="notas" rows="3" maxlength="1000"></textarea></label><div class="total-row"><span>Subtotal</span><strong>${money(cartTotal())}</strong></div><p>El costo de envío y la disponibilidad se confirman al coordinar.</p><button class="button primary" type="submit">${WHATSAPP_NUMBER?'Enviar por WhatsApp':'Preparar pedido'} <span>↗</span></button><div class="prepared-message" hidden></div></form>`;Object.entries(checkoutData).forEach(([k,v])=>{let input=$('#checkout-form').elements.namedItem(k);if(input)input.value=v});$('#back-to-cart').onclick=()=>{checkoutData=Object.fromEntries(new FormData($('#checkout-form')));renderCart()};$('#checkout-form').onsubmit=e=>{e.preventDefault();checkoutData=Object.fromEntries(new FormData(e.target));let lines=cart.map(i=>{let p=P.find(p=>p.id===i.id);return `• ${p.name} — Talle ${i.size} — Color ${p.colorNames[p.colors.indexOf(i.color)]} — ${i.qty} u. — ${money(p.price*i.qty)}`}).join('\n');let msg=`Hola Uniformes SB, quiero consultar por este pedido:\n\n${lines}\n\nSubtotal: ${money(cartTotal())}\nEnvío y disponibilidad a confirmar.\n\nNombre: ${checkoutData.nombre}\nTeléfono: ${checkoutData.telefono}\nDirección: ${checkoutData.direccion}\nLocalidad / Provincia: ${checkoutData.localidad}\nNotas: ${checkoutData.notas||'—'}`;prepareMessage(msg,e.target.querySelector('.prepared-message'))}}
function prepareMessage(message,container){if(/^\d{8,15}$/.test(WHATSAPP_NUMBER)){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');return}container.hidden=false;container.innerHTML='<strong>Tu mensaje está listo.</strong><p>El contacto de WhatsApp estará disponible próximamente. Podés copiar el mensaje para compartirlo. Todavía no se envió.</p><textarea readonly aria-label="Mensaje preparado"></textarea><button type="button" class="button primary">Copiar mensaje</button>';container.querySelector('textarea').value=message;container.querySelector('button').onclick=async()=>{let field=container.querySelector('textarea');try{await navigator.clipboard.writeText(message);toast('Mensaje copiado')}catch{field.focus();field.select();toast('Seleccioná y copiá el mensaje')}};container.scrollIntoView({behavior:'smooth',block:'nearest'})}
$('#filters').onclick=e=>{let b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;filters();products()};
$('#products').onclick=e=>{let fav=e.target.closest('[data-favorite]');if(fav){let id=+fav.dataset.favorite;if(favorites.has(id))favorites.delete(id);else favorites.add(id);persist('sb-favorites',[...favorites]);fav.setAttribute('aria-pressed',favorites.has(id));if(favoritesOnly)products();return}let detail=e.target.closest('[data-detail]');if(detail){details(+detail.dataset.detail);return}let addButton=e.target.closest('[data-add]');if(addButton){add(+addButton.dataset.add);return}let c=e.target.closest('[data-color]');if(c){let card=c.closest('.product');selections.get(+card.dataset.id).color=c.dataset.color;card.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',b===c))}};
$('#products').onchange=e=>{if(e.target.matches('[data-size]'))selections.get(+e.target.closest('.product').dataset.id).size=e.target.value};
$('#cart-view').onclick=e=>{let q=e.target.closest('[data-qty]'),r=e.target.closest('[data-remove]');if(q){let item=cart[+q.dataset.qty];item.qty=Math.min(99,item.qty+(+q.dataset.delta));cart=cart.filter(i=>i.qty>0);sync();renderCart()}if(r){cart.splice(+r.dataset.remove,1);sync();renderCart()}};
$$('[data-cart]').forEach(b=>b.onclick=()=>{renderCart();show($('#cart-dialog'))});$$('[data-contact]').forEach(b=>b.onclick=()=>show($('#contact-dialog')));$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){let rect=d.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)d.close()}}));
$('#view-toggle').onclick=()=>{grid=!grid;document.body.classList.toggle('grid-view',grid);$('#view-toggle').setAttribute('aria-pressed',grid);$('#view-toggle').setAttribute('aria-label',grid?'Ver a pantalla completa':'Ver en cuadrícula');$('#view-toggle').innerHTML=icon(grid?'layers':'grid');$('#products').scrollTop=0};
function searchVisibility(open){$('#search-panel').hidden=!open;$('#search-toggle').setAttribute('aria-expanded',open);if(open)$('#search').focus();else{query='';$('#search').value='';products()}}
$('#search-toggle').onclick=()=>searchVisibility($('#search-panel').hidden);$('#search-close').onclick=()=>searchVisibility(false);$('#search').oninput=e=>{query=e.target.value;products()};$('#sort').onchange=e=>{sort=e.target.value;products()};
function reset(){filter='Todos';query='';favoritesOnly=false;$('#search').value='';$('#mobile-home').classList.add('active');$('#mobile-favorites').classList.remove('active');filters();products()}
$('#reset-filters').onclick=reset;$('#mobile-home').onclick=reset;$('#mobile-favorites').onclick=()=>{favoritesOnly=true;filter='Todos';query='';$('#search').value='';$('#mobile-home').classList.remove('active');$('#mobile-favorites').classList.add('active');filters();products()};$('#contact-form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);prepareMessage(`Hola Uniformes SB, soy ${f.get('nombre')}.\n\n${f.get('mensaje')}`,$('#contact-dialog .prepared-message'))};
hydrateIcons();filters();products();sync();setTimeout(()=>$('.loader').classList.add('done'),550);


